export const jsonFormFintech = [
    { "formFintech":"onHold", "label": "Folio de la solicitud" },
    { "formFintech":"onHold", "label": "Nombre" },
    { "formFintech":"onHold", "label": "Apellido paterno" },
    { "formFintech":"onHold", "label": "Apellido materno" },
    { "formFintech":"onHold", "label": "ID Empleado" },
    { "formFintech":"onHold", "label": "Empresa asignada" },
    { "formFintech":"onHold", "label": "Proyecto" },
    { "formFintech":"onHold", "label": "Correo del cliente" },
    { "formFintech":"onHold", "label": "Correo del responsable de proyecto" },
    { "formFintech":"onHold", "label": "Periodo de pago" },
    { "formFintech":"onHold", "label": "Fecha inicio de periodo" },
    { "formFintech":"onHold", "label": "Pago de ingresos" },
    { "formFintech":"onHold", "label": "Días laborados" },
    { "formFintech":"onHold", "label": "Monto solicitado" },
    { "formFintech":"onHold", "label": "Comisión por préstamo" },
    { "formFintech":"onHold", "label": "Moto a depositar" },
    { "formFintech":"onHold", "label": "Fecha de solicitud" },
    { "formFintech":"onHold", "label": "Hora de solicitud" },
    { "formFintech":"onHold", "label": "Pago próximo de ingresos" },
    { "formFintech":"onHold", "label": "Rechazar/Aprobar" },

    { "formFintech":"approved", "label":"Nombre" },
    { "formFintech":"approved", "label":"Apellido paterno" },
    { "formFintech":"approved", "label":"Apellido materno" },
    { "formFintech":"approved", "label":"ID Empleado" },
    { "formFintech":"approved", "label":"Empresa asignada" },
    { "formFintech":"approved", "label":"Correo del cliente" },
    { "formFintech":"approved", "label":"Correo del responsable de proyecto" },
    { "formFintech":"approved", "label":"Proyecto" },
    { "formFintech":"approved", "label":"Periodo de pago" },
    { "formFintech":"approved", "label":"Fecha inicio de periodo" },
    { "formFintech":"approved", "label":"Pago de ingreso" },
    { "formFintech":"approved", "label":"Folio de la solicitud" },
    { "formFintech":"approved", "label":"Autorizado por" },
    { "formFintech":"approved", "label":"Monto solicitado" },
    { "formFintech":"approved", "label":"Comisión por préstamo" },
    { "formFintech":"approved", "label":"Moto a depositar" },
    { "formFintech":"approved", "label":"Fecha de solicitud" },
    { "formFintech":"approved", "label":"Hora de solicitud" },
    { "formFintech":"approved", "label":"Fecha de la aprobación" },
    { "formFintech":"approved", "label":"Hora de la aprobación" },
    { "formFintech":"approved", "label":"Folio SWAP" },
    { "formFintech":"approved", "label":"Fecha de la respuesta de SWAP" },
    { "formFintech":"approved", "label":"Hora de la respuesta de SWAP" },
    { "formFintech":"approved", "label":"Pago próximo ingresos" },
    { "formFintech":"approved", "label":"Folio confirmación de SICO" },
    { "formFintech":"approved", "label":"Resultado de la operación SICO" },
    { "formFintech":"approved", "label":"Descripción de la operación SICO" },

    { "formFintech":"rejected", "label":"Nombre" },
    { "formFintech":"rejected", "label":"Apellido paterno" },
    { "formFintech":"rejected", "label":"Apellido materno" },
    { "formFintech":"rejected", "label":"ID Empleado" },
    { "formFintech":"rejected", "label":"Empresa asignada" },
    { "formFintech":"rejected", "label":"Proyecto" },
    { "formFintech":"rejected", "label":"Correo del cliente" },
    { "formFintech":"rejected", "label":"Correo del responsable de proyecto" },
    { "formFintech":"rejected", "label":"Periodo de pago" },
    { "formFintech":"rejected", "label":"Fecha inicio de periodo" },
    { "formFintech":"rejected", "label":"Pago de nómina" },
    { "formFintech":"rejected", "label":"Folio de la solicitud" },
    { "formFintech":"rejected", "label":"Monto solicitado" },
    { "formFintech":"rejected", "label":"Comisión por prestamos" },
    { "formFintech":"rejected", "label":"Moto a depositar" },
    { "formFintech":"rejected", "label":"Fecha de solicitud" },
    { "formFintech":"rejected", "label":"Hora de solicitud" },
    { "formFintech":"rejected", "label":"Fecha de la aprobación" },
    { "formFintech":"rejected", "label":"Hora de la aprobación" },
    { "formFintech":"rejected", "label":"Fecha de la respuesta de SWAP" },
    { "formFintech":"rejected", "label":"Hora de la respuesta de SWAP" },
    { "formFintech":"rejected", "label":"Pago próxima nomina" },
    { "formFintech":"rejected", "label":"Rechazado por" },
    { "formFintech":"rejected", "label":"Motivo de rechazo" },
    { "formFintech":"rejected", "label":"Entidad" },
];
