version: '3'
services:
  frontend:
    build:
      context: .
      dockerfile: "Dockerfile-frontend"
    ports:
      - "8100:80"
    networks:
      - rhtotalqanet
  eurekaservice:
    build:
      context: .
      dockerfile: "Dockerfile-eureka-service"
    ports:
      - "9761:8761"
    networks:
      - rhtotalqanet
  gatewayservice:
    build:
      context: .
      dockerfile: "Dockerfile-gateway-service"
    ports:
      - "9000:9000"
    networks:
      - rhtotalqanet
    environment:
      - CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS:-http://localhost:*}
    depends_on:
      - eurekaservice
  securityservice:
    build:
      context: .
      dockerfile: "Dockerfile-security-service"
    ports:
      - "9090:9090"
    networks:
      - rhtotalqanet
    environment:
      - TZ=America/Mexico_City
      - DB_PASS=${DB_PASS:-project123}
      - AES_SECRET_KEY=${AES_SECRET_KEY}
    depends_on:
      - eurekaservice
      - gatewayservice
  applicationservice:
    build:
      context: .
      dockerfile: "Dockerfile-application-service"
    ports:
      - "9091:9091"
    networks:
      - rhtotalqanet
    environment:
      - TZ=America/Mexico_City
      - DB_PASS=${DB_PASS:-project123}
    depends_on:
      - eurekaservice
      - gatewayservice
  userservice:
    build:
      context: .
      dockerfile: "Dockerfile-user-service"
    ports:
      - "9092:9092"
    networks:
      - rhtotalqanet
    environment:
      - TZ=America/Mexico_City
      - DB_PASS=${DB_PASS:-project123}
      - AES_SECRET_KEY=${AES_SECRET_KEY}
    depends_on:
      - eurekaservice
      - gatewayservice
      - securityservice
networks:
  rhtotalqanet:
