version: '3'
services:
  web-admin:
    build:
      context: .
      dockerfile: "Dockerfile-web-admin"
    ports:
      - "80:80"
    networks:
      - dchnet
  eurekaservice:
    build:
      context: .
      dockerfile: "Dockerfile-eureka-service"
    ports:
      - "8761:8761"
    networks:
      - dchnet
  gatewayservice:
    build:
      context: .
      dockerfile: "Dockerfile-gateway-service"
    ports:
      - "8000:8000"
    networks:
      - dchnet
    environment:
      - CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS:-http://localhost:*}
    depends_on:
      - eurekaservice
  postgres:
    build:
      context: .
      dockerfile: "Dockerfile-postgresql"
    ports:
      - "5432:5432"
    networks:
      - dchnet
    environment:
      - POSTGRES_PASSWORD=${DB_PASS:-project123}
  securityservice:
    build:
      context: .
      dockerfile: "Dockerfile-security-service"
    ports:
      - "8090:8090"
    networks:
      - dchnet
    environment:
      - TZ=America/Mexico_City
      - DB_PASS=${DB_PASS:-project123}
      - AES_SECRET_KEY=${AES_SECRET_KEY}
      - CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS:-http://localhost:*}
    depends_on:
      - eurekaservice
      - gatewayservice
      - postgres
  applicationservice:
    build:
      context: .
      dockerfile: "Dockerfile-application-service"
    ports:
      - "8091:8091"
    networks:
      - dchnet
    environment:
      - TZ=America/Mexico_City
      - DB_PASS=${DB_PASS:-project123}
    depends_on:
      - eurekaservice
      - gatewayservice
      - postgres
  userservice:
    build:
      context: .
      dockerfile: "Dockerfile-user-service"
    ports:
      - "8092:8092"
    networks:
      - dchnet
    environment:
      - DB_PASS=${DB_PASS:-project123}
      - AES_SECRET_KEY=${AES_SECRET_KEY}
    depends_on:
      - eurekaservice
      - gatewayservice
      - securityservice
      - postgres
networks:
  dchnet:
