version: '3'
services:
  web-admin:
    build:
      context: .
      dockerfile: "Dockerfile-web-admin"
    ports:
      - "80:80"
    networks:
      - dchnet
  eurekaservice:
    build:
      context: .
      dockerfile: "Dockerfile-eureka-service"
    ports:
      - "8761:8761"
    networks:
      - dchnet
  gatewayservice:
    build:
      context: .
      dockerfile: "Dockerfile-gateway-service"
    ports:
      - "8000:8000"
    networks:
      - dchnet
    depends_on:
      - eurekaservice
  securityservice:
    build:
      context: .
      dockerfile: "Dockerfile-security-service"
    ports:
      - "8090:8090"
    networks:
      - dchnet
    environment:
      - TZ=America/Mexico_City
    depends_on:
      - eurekaservice
      - gatewayservice
  applicationservice:
    build:
      context: .
      dockerfile: "Dockerfile-application-service"
    ports:
      - "8091:8091"
    networks:
      - dchnet
    environment:
      - TZ=America/Mexico_City
    depends_on:
      - eurekaservice
      - gatewayservice
  userservice:
    build:
      context: .
      dockerfile: "Dockerfile-user-service"
    ports:
      - "8092:8092"
    networks:
      - dchnet
    depends_on:
      - eurekaservice
      - gatewayservice
      - securityservice
networks:
  dchnet:
