export class InsuranceTableTO {
    
    idInsurance:string;
    coverage:string;
    policy:string;
    totalPrima:number;
    insurangeType:string;
    nameTypeInsurance:string;
    noCertificate:string;
    urlInsuranceCarrier:string;
    insuranceCarrier: string;
    phoneInsuranceCarrier:string;
    startDate:Date;
    endDate:Date;
    insurancePolicyPdf:string;
    fileName:string;
    timePublication: string;
    notificationTime: string;
    notificationTitle:string;
    notificationDetail:string;
    status:string;
    vehicleDescription:string;
    serialNumber:string;
    plates:string;
    year:string;
    marca:string;
    model:string;
    service:string;
    use:string;
    description:string;
    idTypeInsurance:number;
    scope:string;
    sum:string;
    typeVehicle:string;
    lastUserModifier:string;
    lastModifier:Date;
    active:boolean;
    typePolicy:string;
    creationDate:Date;    
}    