spring:
  application:
    name: eureka-service

server:
  port: 8000

eureka:
  instance:
    hostname: ec2-54-86-23-170.compute-1.amazonaws.com
  client:
    registerWithEureka: false
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

zuul:
  ignoredServices: '*'
  prefix: /api
  routes:
    security:
      path: /security/**
      serviceId: security-service
    application:
      path: /application/**
      serviceId: application-service
    fintech:
      path: /fintech/**
      serviceId: fintech-service
    paysheetsico:
      path: /paysheetsico/**
      serviceId: paysheetsico-service
    user:
      path: /user/**
      serviceId: user-service
  ignored-headers: Access-Control-Allow-Credentials, Access-Control-Allow-Origin

ribbon:
  ReadTimeout: 60000
  ConnectionTimeout: 3000
