spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      routes:
        - id: security-service
          uri: lb://security-service
          predicates:
            - Path=/api/security/**
          filters:
            - StripPrefix=2
        - id: application-service
          uri: lb://application-service
          predicates:
            - Path=/api/application/**
          filters:
            - StripPrefix=2
        - id: fintech-service
          uri: lb://fintech-service
          predicates:
            - Path=/api/fintech/**
          filters:
            - StripPrefix=2
        - id: paysheetsico-service
          uri: lb://paysheetsico-service
          predicates:
            - Path=/api/paysheetsico/**
          filters:
            - StripPrefix=2
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/user/**
          filters:
            - StripPrefix=2
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

server:
  port: 8000

eureka:
  instance:
    ip-address: ${EUREKA_INSTANCE_IP:127.0.0.1}
    hostname: ${EUREKA_HOST:localhost}
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/

springdoc:
  swagger-ui:
    urls:
      - name: security-service
        url: /api/security/v3/api-docs
      - name: application-service
        url: /api/application/v3/api-docs
      - name: fintech-service
        url: /api/fintech/v3/api-docs
      - name: user-service
        url: /api/user/v3/api-docs
      - name: paysheetsico-service
        url: /api/paysheetsico/v3/api-docs

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway
  endpoint:
    gateway:
      enabled: true

logging:
  level:
    root: INFO
    mx.com.axity.gateway: DEBUG
    org.springframework.cloud.gateway: DEBUG
