# Equivalente al groupId de Maven
sonar.projectKey=18_WorkPoint_RHTotal_Security

# Equivalente al artifactId de Maven
sonar.projectName=18_WorkPoint_RHTotal_Security

# Equivalente a la versión de Maven
sonar.projectVersion=1.0

# Directorio donde resida el código fuente a analizar
sonar.sources=security-service/security-commons/src/main/java,security-service/security-model/src/main/java,security-service/security-persistence/src/main/java,security-service/security-services/src/main/java,security-service/security-web/src/main/java

# Lenguaje que a analizar (Java por defecto)
sonar.language=java

# Comma-separated paths to directories with tests
sonar.tests=security-service/security-commons/src/test/java,security-service/security-model/src/test/java,security-service/security-persistence/src/test/java,security-service/security-services/src/test/java

# Comma-separated paths to directories containing the compiled bytecode files corresponding to your source files
sonar.java.binaries=security-service/security-commons/target/classes,security-service/security-model/target/classes,security-service/security-persistence/target/classes,security-service/security-services/target/classes,security-service/security-web/target/classes

# Encoding de código fuente
sonar.sourceEncoding=UTF-8

# Sonar test coverage
#sonar.jacoco.reportPath=target/coverage-reports/jacoco-unit.exec
#sonar.java.coveragePlugin=jacoco