<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>mx.com.axity</groupId>
    <artifactId>user</artifactId>
    <version>1.0-SNAPSHOT</version>
    <modules>
        <module>user-web</module>
        <module>user-services</module>
        <module>user-persistence</module>
        <module>user-model</module>
        <module>user-commons</module>
    </modules>
    <packaging>pom</packaging>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <snapshot.version>1.0-SNAPSHOT</snapshot.version>
        <java.version>21</java.version>
        <maven.compiler.source>21</maven.compiler.source>
        <maven.compiler.target>21</maven.compiler.target>
        <maven.compiler.release>21</maven.compiler.release>
        <spring.version>3.2.5</spring.version>
        <spring-cloud.version>2023.0.1</spring-cloud.version>
        <modelmapper.version>3.2.0</modelmapper.version>
        <h2db.version>2.2.224</h2db.version>
        <postgresql.version>42.7.3</postgresql.version>
        <springdoc.version>2.5.0</springdoc.version>
        <gson.version>2.10.1</gson.version>
    </properties>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>mx.com.axity</groupId>
                <artifactId>user-commons</artifactId>
                <version>${snapshot.version}</version>
            </dependency>
            <dependency>
                <groupId>mx.com.axity</groupId>
                <artifactId>user-model</artifactId>
                <version>${snapshot.version}</version>
            </dependency>
            <dependency>
                <groupId>mx.com.axity</groupId>
                <artifactId>user-persistence</artifactId>
                <version>${snapshot.version}</version>
            </dependency>
            <dependency>
                <groupId>mx.com.axity</groupId>
                <artifactId>user-services</artifactId>
                <version>${snapshot.version}</version>
            </dependency>
            <dependency>
                <groupId>mx.com.axity</groupId>
                <artifactId>user-web</artifactId>
                <version>${snapshot.version}</version>
            </dependency>
            <dependency>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-starter-parent</artifactId>
                <version>${spring.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>org.springframework.cloud</groupId>
                <artifactId>spring-cloud-dependencies</artifactId>
                <version>${spring-cloud.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>org.springdoc</groupId>
                <artifactId>springdoc-openapi-starter-webmvc-ui</artifactId>
                <version>${springdoc.version}</version>
            </dependency>
            <dependency>
                <groupId>org.modelmapper</groupId>
                <artifactId>modelmapper</artifactId>
                <version>${modelmapper.version}</version>
            </dependency>
            <dependency>
                <groupId>org.postgresql</groupId>
                <artifactId>postgresql</artifactId>
                <version>${postgresql.version}</version>
            </dependency>
            <dependency>
                <groupId>com.h2database</groupId>
                <artifactId>h2</artifactId>
                <version>${h2db.version}</version>
                <scope>test</scope>
            </dependency>
            <dependency>
                <groupId>com.google.code.gson</groupId>
                <artifactId>gson</artifactId>
                <version>${gson.version}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>

</project>
