server:
  port: ${EUREKA_PORT:8000}

spring:
  application:
    name: eureka-service

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8000}/eureka
  server:
    enable-self-preservation: true
    eviction-interval-timer-in-ms: 5000

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

logging:
  level:
    root: INFO
    com.netflix.eureka: WARN
    com.netflix.discovery: WARN
